# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('saving', 'saving'), ('withdrawal', 'withdrawal'), ('airtime', 'airtime')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('reference_code', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UssdUser',
            fields=[
                ('msisdn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('network', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('goal_item', models.CharField(max_length=128)),
                ('goal_amount', models.IntegerField(blank=True, null=True)),
                ('recurring_amount', models.IntegerField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('amount', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('distributor', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ussd.UssdUser')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ussd.UssdUser'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ussd.Voucher'),
        ),
    ]
