# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0004_add_transaction_action_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('saving', 'saving'), ('withdrawal', 'withdrawal'), ('airtime', 'airtime'), ('rewards', 'rewards'), ('registration bonus', 'registration bonus'), ('quiz_prize', 'quiz_prize')], max_length=32),
        ),
    ]
