# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_auto_20161106_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.CharField(default='add description', max_length=255),
            preserve_default=False,
        ),
    ]
